# This is a basic workflow to help you get started with Actions
name: Releases

# Controls when the workflow will run
on:
  push:
    # Triggers the workflow on push or pull request events but only for the tagged
    tags:
      - '*'

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  releases:
    name: release apk
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: "11.0"
      FLUTTER_VERSION: "2.10.5"
    steps:
      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: ${{env.JAVA_VERSION}}
#      - uses: subosito/flutter-action@v2
#        with:
#          flutter-version: ${{env.FLUTTER_VERSION}}
#      - run: flutter pub get
##      - run: flutter analyze
##      - run: flutter test
#      - run: flutter build apk --release
#      - uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/flutter-apk/*.apk"
#          token: ${{ secrets.GITHUB_TOKEN }}
      - name: send default message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
#          message: |
#            ${{ github.actor }} created commit
#
#            Repository: ${{ github.repository }}
#            Workspace: ${{ github.workspace }}

#            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          photo: ./assets/images/splash_logo.png
          document: ./assets/images/splash_logo.png
          message: |
            Below is the apk for commit: ${{ github.event.head_commit.message }}

  notify:
    if: cancelled() == false
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: up9cloud/action-notify@master
        env:
          GITHUB_JOB_STATUS: ${{ needs.deploy.result }}
          TELEGRAM_BOT_TOKEN: ${{secrets.TELEGRAM_TOKEN}}
          TELEGRAM_CHAT_ID: ${{secrets.TELEGRAM_TO}}
          # Custom template file path, relative to the repo root
          TELEGRAM_TEMPLATE_PATH: ".assets/images/splash_logo.png"
          # Custom env, assign it from [GitHub context](https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#contexts)
          CUSTOM_VAR1: ${{github.repository_owner}}
          CUSTOM_VAR2: "a custom variable"





